#!/bin/bash
apt install figlet -y > /dev/null 2>&1
clear
figlet Installing
curl -LO https://raw.githubusercontent.com/Anon4You/AndroVirus/main/androvirus
mv androvirus $PREFIX/bin
chmod 777 $PREFIX/bin/androvirus
clear
figlet installed
echo now you can run the tool
echo "by typing"$'\e[32;1m'" androvirus"
