#!/bin/bash
echo $'\e[32;1m'"---installing python figlet toilet"$'\e[0m'
apt install python figlet toilet -y
echo $'\e[32;1m'"---installing androvirus"$'\e[0m'
curl -LO https://raw.githubusercontent.com/Anon4You/AndroVirus/main/androvirus
mv androvirus $PREFIX/bin
chmod 777 $PREFIX/bin/androvirus
clear
figlet -f smblock Installed
echo now you can run the tool
echo "by typing"$'\e[32;1m'" androvirus"
